name: Publish the extension

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - .gitignore
      - .vscodeignore
      - .prettierrc.mjs
      - .vscode/**
      - img/**
      - .github/workflows/build.yaml
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10'
          run_install: false

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Install VSCE
      - name: Install VSCE
        run: pnpm install -g @vscode/vsce

      # Install OVSX
      - name: Install OVSX
        run: pnpm install -g ovsx

      # Package and publish the theme
      - name: Publish to VSCode Marketplace
        run: vsce publish -p ${{ secrets.LUMEN_VSCE_TOKEN}}

      # Package and publish the theme
      - name: Publish to Open VSIX Registry
        run: ovsx publish -p ${{ secrets.LUMEN_OVSX_TOKEN}}
